function [dX] = Ind2Derivatives(dxdt) 
% gives the value to the species names from the corresponding index in the vector X 
dX(1 , 1) = dxdt.m_r; 
dX(2 , 1) = dxdt.m_t; 
dX(3 , 1) = dxdt.m_m; 
dX(4 , 1) = dxdt.m_q; 
dX(5 , 1) = dxdt.m_p; 
dX(6 , 1) = dxdt.rm_r; 
dX(7 , 1) = dxdt.rm_t; 
dX(8 , 1) = dxdt.rm_m; 
dX(9 , 1) = dxdt.rm_q; 
dX(10 , 1) = dxdt.rm_p; 
dX(11 , 1) = dxdt.zm_r; 
dX(12 , 1) = dxdt.zm_t; 
dX(13 , 1) = dxdt.zm_m; 
dX(14 , 1) = dxdt.zm_q; 
dX(15 , 1) = dxdt.zm_p; 
dX(16 , 1) = dxdt.e_r; 
dX(17 , 1) = dxdt.e_t; 
dX(18 , 1) = dxdt.e_m; 
dX(19 , 1) = dxdt.e_q; 
dX(20 , 1) = dxdt.e_p; 
dX(21 , 1) = dxdt.s_i; 
dX(22 , 1) = dxdt.a; 
